### ISSUE TITLE
 'Auth0Authenticator' object has no attribute 'keys' (minor bug)

### ISSUE THREAD

**Issue by philippegirard** [Sytten/flask-rebar-auth0#2]
if you add a key to the Auth0Authenticator before running the  ` init_app` method you get an error : 
```
authenticator = Auth0Authenticator(app)
authenticator._add_key(keys)
authenticator.init_app()

# *** AttributeError: 'Auth0Authenticator' object has no attribute 'keys'
```

You have to do the following
```
authenticator = Auth0Authenticator(app)
authenticator.init_app()
authenticator._add_key(keys)

# no error
```

The self.keys should be created in the constructor
Otherwise, the documentation should be updated accordingly in the readme.

Maybe a test should be added to simulate better the flow of someone that wants to test this plugin.

ref : https://github.com/Sytten/flask-rebar-auth0/blob/master/flask_rebar_auth0/authenticator.py#L74

**Comment by Sytten** [comment]
This is not true though, if you pass `app` in the constructor the `init_app` is called automatically and creates the keys dict, the README is correct. But I agree that since this is designed for testing it should be convenient, so I will init the variable and make the function public.

**Comment by Sytten** [comment]
Fixed
